FROM node:20.17.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build:admin-panel

FROM node:20.17.0 AS runner

WORKDIR /app

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./
COPY --from=builder /app/.next ./.next

RUN yarn install --production --frozen-lockfile

EXPOSE ${NEXT_PUBLIC_ADMIN_PORT}

CMD ["yarn", "start"]